export const Regions = [
  // 📍 DKI Jakarta
  { name: "Kota Jakarta Pusat", province: "DKI Jakarta" },
  { name: "Kota Jakarta Utara", province: "DKI Jakarta" },
  { name: "Kota Jakarta Barat", province: "DKI Jakarta" },
  { name: "Kota Jakarta Selatan", province: "DKI Jakarta" },
  { name: "Kota Jakarta Timur", province: "DKI Jakarta" },

  // 📍 Jawa Barat
  { name: "Kabupaten Bandung", province: "Jawa Barat" },
  { name: "Kota Bandung", province: "Jawa Barat" },
  { name: "Kabupaten Bekasi", province: "Jawa Barat" },
  { name: "Kota Bekasi", province: "Jawa Barat" },
  { name: "Kabupaten Bogor", province: "Jawa Barat" },
  { name: "Kota Bogor", province: "Jawa Barat" },
  { name: "Kabupaten Cianjur", province: "Jawa Barat" },
  { name: "Kabupaten Cirebon", province: "Jawa Barat" },
  { name: "Kota Cirebon", province: "Jawa Barat" },
  { name: "Kabupaten Garut", province: "Jawa Barat" },
  { name: "Kabupaten Indramayu", province: "Jawa Barat" },
  { name: "Kabupaten Karawang", province: "Jawa Barat" },
  { name: "Kabupaten Kuningan", province: "Jawa Barat" },
  { name: "Kabupaten Majalengka", province: "Jawa Barat" },
  { name: "Kabupaten Purwakarta", province: "Jawa Barat" },
  { name: "Kabupaten Subang", province: "Jawa Barat" },
  { name: "Kabupaten Sukabumi", province: "Jawa Barat" },
  { name: "Kota Sukabumi", province: "Jawa Barat" },
  { name: "Kabupaten Sumedang", province: "Jawa Barat" },
  { name: "Kabupaten Tasikmalaya", province: "Jawa Barat" },
  { name: "Kota Tasikmalaya", province: "Jawa Barat" },
  { name: "Kabupaten Pangandaran", province: "Jawa Barat" },

  // 📍 Banten
  { name: "Kabupaten Pandeglang", province: "Banten" },
  { name: "Kabupaten Lebak", province: "Banten" },
  { name: "Kabupaten Tangerang", province: "Banten" },
  { name: "Kota Tangerang", province: "Banten" },
  { name: "Kota Tangerang Selatan", province: "Banten" },
  { name: "Kota Serang", province: "Banten" },
  { name: "Kabupaten Serang", province: "Banten" },

  // 📍 Jawa Tengah
  { name: "Kabupaten Boyolali", province: "Jawa Tengah" },
  { name: "Kabupaten Klaten", province: "Jawa Tengah" },
  { name: "Kota Surakarta", province: "Jawa Tengah" },
  { name: "Kabupaten Karanganyar", province: "Jawa Tengah" },
  { name: "Kabupaten Sragen", province: "Jawa Tengah" },
  { name: "Kabupaten Sukoharjo", province: "Jawa Tengah" },
  { name: "Kabupaten Wonogiri", province: "Jawa Tengah" },
  { name: "Kabupaten Semarang", province: "Jawa Tengah" },
  { name: "Kota Semarang", province: "Jawa Tengah" },
  { name: "Kabupaten Kudus", province: "Jawa Tengah" },
  { name: "Kabupaten Pati", province: "Jawa Tengah" },
  { name: "Kabupaten Jepara", province: "Jawa Tengah" },
  { name: "Kabupaten Banyumas", province: "Jawa Tengah" },
  { name: "Kota Tegal", province: "Jawa Tengah" },
  { name: "Kabupaten Tegal", province: "Jawa Tengah" },
  { name: "Kabupaten Pemalang", province: "Jawa Tengah" },
  { name: "Kabupaten Brebes", province: "Jawa Tengah" },
  { name: "Kabupaten Wonosobo", province: "Jawa Tengah" },
  { name: "Kabupaten Magelang", province: "Jawa Tengah" },
  { name: "Kota Magelang", province: "Jawa Tengah" },
  { name: "Kabupaten Purworejo", province: "Jawa Tengah" },

  // 📍 DI Yogyakarta
  { name: "Kabupaten Sleman", province: "DI Yogyakarta" },
  { name: "Kabupaten Bantul", province: "DI Yogyakarta" },
  { name: "Kabupaten Kulon Progo", province: "DI Yogyakarta" },
  { name: "Kabupaten Gunungkidul", province: "DI Yogyakarta" },
  { name: "Kota Yogyakarta", province: "DI Yogyakarta" },

  // 📍 Jawa Timur
  { name: "Kota Surabaya", province: "Jawa Timur" },
  { name: "Kabupaten Sidoarjo", province: "Jawa Timur" },
  { name: "Kabupaten Gresik", province: "Jawa Timur" },
  { name: "Kabupaten Lamongan", province: "Jawa Timur" },
  { name: "Kabupaten Mojokerto", province: "Jawa Timur" },
  { name: "Kota Mojokerto", province: "Jawa Timur" },
  { name: "Kabupaten Jombang", province: "Jawa Timur" },
  { name: "Kabupaten Malang", province: "Jawa Timur" },
  { name: "Kota Malang", province: "Jawa Timur" },
  { name: "Kabupaten Blitar", province: "Jawa Timur" },
  { name: "Kota Blitar", province: "Jawa Timur" },
  { name: "Kabupaten Kediri", province: "Jawa Timur" },
  { name: "Kota Kediri", province: "Jawa Timur" },
  { name: "Kabupaten Tulungagung", province: "Jawa Timur" },
  { name: "Kabupaten Banyuwangi", province: "Jawa Timur" },
  { name: "Kabupaten Jember", province: "Jawa Timur" },
  { name: "Kabupaten Probolinggo", province: "Jawa Timur" },
  { name: "Kota Probolinggo", province: "Jawa Timur" },
  { name: "Kabupaten Pasuruan", province: "Jawa Timur" },
  { name: "Kota Pasuruan", province: "Jawa Timur" },
  { name: "Kabupaten Madiun", province: "Jawa Timur" },
  { name: "Kota Madiun", province: "Jawa Timur" },
  { name: "Kabupaten Magetan", province: "Jawa Timur" },
  { name: "Kabupaten Ngawi", province: "Jawa Timur" },
  { name: "Kabupaten Ponorogo", province: "Jawa Timur" },
  { name: "Kabupaten Trenggalek", province: "Jawa Timur" },
  { name: "Kabupaten Pacitan", province: "Jawa Timur" },
];
